# Generated by Django 4.1 on 2022-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('pat_code', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
