# Generated by Django 4.1 on 2022-08-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('pat_code', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=15)),
                ('prescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
