# Generated by Django 4.1 on 2022-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_register', '0002_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
